services:
  # Backend API Service
  - type: web
    name: parksphere-api
    runtime: docker
    rootDir: .
    dockerfilePath: ./parksphere/server/Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: NASA_API_KEY
        sync: false
      - key: NPS_API_KEY
        sync: false
    healthCheckPath: /api/health
    
  # Frontend Service
  - type: web
    name: parksphere-frontend
    runtime: docker
    rootDir: .
    dockerfilePath: ./parksphere/client/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://parksphere-api.onrender.com
      - key: PORT
        value: 3000