services:
  - type: web
    name: parksphere
    runtime: node
    buildCommand: cd parksphere/client && npm install && npm run build
    startCommand: cd parksphere/client && npm start
    rootDir: .
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NEXT_PUBLIC_API_URL
        value: http://localhost:8000
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: UNSPLASH_SECRET_KEY
        sync: false
      - key: UNSPLASH_APPLICATION_ID
        sync: false
      - key: NASA_API_KEY
        sync: false
      - key: NPS_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false